-- DEPRECATED — not used anymore.
--
-- This schema now lives at netlify/database/migrations/0001_init.sql,
-- which Netlify applies automatically on deploy (no manual step needed).
--
-- You can delete this whole db/ folder — safe to remove.
